services:
  - type: web
    name: subscription-payments-manager-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run api:prod
    autoDeploy: true
  - type: web
    name: subscription-payments-manager-web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/subscription-payments-manager/browser
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
